import Head from "next/head";
import MenuPods from "../components/menuPods";

export default function Home() {
  return (
    <>
      <Head>
        <title>Actríz Karla Garrido</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="image-container">
          <div className="main-text-container">
            <h1>
              Karla Garrido <span>Actriz</span>
            </h1>
            <MenuPods />
          </div>
        </div>
      </main>
      <style jsx global>
        {`
          .main-text-container {
            position: fixed;
            top: 50%;
            width: 100%;
          }

          @media (min-width: 960px) {
            .main-text-container {
              top: 40%;
            }
          }
        `}
      </style>
      <style jsx>
        {`
          main {
            height: 100vh;
            background-image: url("https://storage.googleapis.com/karlagarrido/landing/karla_garrido_sm.png");
            background-size: 100vh;
            background-position: center;
            background-repeat: no-repeat;
            background-color: rgba(137, 121, 113, 255);
          }

          h1 {
            font-size: 46px;
            text-align: center;
            font-weight: 900;
          }

          span {
            display: block;
            text-align: center;
            font-size: 28px;
          }

          @media (min-width: 600px) {
            h1 {
              font-size: 64px;
            }
          }

          @media (min-width: 960px) {
            main {
              background-image: url("https://storage.googleapis.com/karlagarrido/landing/karla_garrido_actriz.jpg");
              background-size: cover;
            }

            h1 {
              font-size: 96px;
              text-align: start;
              width: 90vw;
              margin: 64px auto 25px auto;
            }

            span {
              font-size: 56px;
              text-align: start;
            }
          }
        `}
      </style>
    </>
  );
}
